### PR TITLE
Added dihedral_matrix and Shukla-Fig2 plotting

### PR DESCRIPTION
**Pull request by sonyahanson**
My matrix is wrong, it is not getting the same answer as [the original dihedral plot](https://github.com/choderalab/octomore/blob/master/dihedral-plot/DFG_dihedral_plot_original.py). But it does work.

### CODE REVIEW

**Comment by sonyahanson** [comment]
Abl_AD and Src_AD are the dihedrals investigated in the original plot...

**Comment by sonyahanson** [comment]
Note that there is now a better version of Shukla plotting in https://github.com/choderalab/kinalysis

**Comment by sonyahanson** [comment]
Added some new plots of 11400 and 11401 ('new' simulations) showing lines where starting structures were, and there's some indication that we probably see DFG out-in transition! This is all still using the same dihedral angle as in the original dihedral plot...

src_dfg_dihedral_hist_newsims_nyas

**Comment by dwhswenson** [comment]
Nice!

Where do the starting structures come from? (Expt PDB, I assume?) Interesting that some (purple furthest to right) are clearly not well-minimized.

Any idea about the significance of the two minor peaks to the left? They're clearly different between the two.

Let me know if you'd like OPS-based ways to identify the transition trajectory. We have some tools of potential use, but it might be as easy (or faster) to do without OPS.

I think I started a branch to add some TPS based on the existing Octomore.py (writing from phone now). I'll make sure to make that into a proper PR soon!

**Comment by sonyahanson** [comment]
Yes. The starting structures are just from the PDB. Most likely all Src structures (they're ranked by sequence identity).

Not sure about the two minor peaks. Honestly hadn't noticed the blue one, could be interesting to check out! The green one seems to be just a tail of the larger DFG-in peak.

Just made the ugliest figure ever that separates each of the Src DFG-out sims by this coordinate. Seems like the green peak is just from one simulation. (The numbers here are the run# of the simulation analyzed.)

src_dfg_dihedral_hist_newsims_out_byrun

**Comment by sonyahanson** [comment]
I'm thinking about cleaning this strange conglomeration of plots up a bit and merging over the weekend. I don't think the 'dihedral matrix' thing I was looking at and is obviously buggy is particularly worth fixing.

**Comment by sonyahanson** [comment]
Going to go ahead and merge.

**Pull request merged**
