### PR TITLE
Get initial transition trajectory from FAH data

### PR DESCRIPTION
**Pull request by dwhswenson**
At the very least, this will show how to do this sort of thing with OPS. (And with the current setup, I suggest using OPS -- the speed is good enough for the first trajectory, which I already tried. Plus, it takes about 5 lines of code.) 

Right now, I'm plotting order parameter (Roux's DFG dihedral) as a function of time. View the added ipynb to see it. I think the existing hops are actually just circling through the periodic boundary, not genuinely landing in the other state.

Once I find a trajectory that seems to have a transition, I'll show how to do that (also really easy). Basic plan:
- [x] Plot order parameters for one file as function of time
- [x] Find clean way to access FAH data via scripts (I assume whatever @sonyahanson is doing can also work for me)
- [x] Find trajectory that had transition
- [x] Use `Ensemble.split` to get the transition segment
- [x] Add tricks to analyze quality of state definitions
- [x] Clean up histogram presentation

### CODE REVIEW

**Comment by dwhswenson** [comment]
I'm adding some new features to OPS that will be used in this PR. The OPS additions are in https://github.com/choderalab/openpathsampling/pull/435. 

So (1) that PR needs to be finished before this one; (2) you'll need to update your OPS install after that PR gets merged into OPS.

**Comment by jchodera** [comment]
I wonder if we can use something like this to push our munged FAH data to
figshare automagically and make it easier for people to access for things
like OPS: http://openresearchsoftware.metajnl.com/article/10.5334/jors.bj/

**Comment by dwhswenson** [comment]
@jchodera : Interesting. I wasn't aware of figshare -- good to know about. I've been thinking about trying to find a good way to encourage people to make their OPS scripts more accessible to a broader audience: it would go beyond figshare, but adding support for something like PyRDM might be a nice way for us (especially as developers creating new methods) to start. I'll open on an issue on OPS (after I read the PyRDM article in more detail, and not for a few days or even a couple weeks) -- it won't make the 1.0, but having the issue in our list will ensure that @jhprinz and I keep it in mind for later.

**Comment by jchodera** [comment]
msmbuilder hosts some large example datasets on FigShare and [uses a simple scheme](https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/example_datasets/alanine_dipeptide.py) to retrieve them.  

Even better would be to have some way for simulations to automatically stow data somewhere as it is being generated/received/munged and make it easy for OPS to both grab the datasets to start with and stow new data.

**Comment by dwhswenson** [comment]
Okay. This is ready for review and merge. I've identified a few frames we could start from in order to do the path sampling. The pictures in the notebook aren't all the prettiest, but they tell the story well enough. The documentation is also a bit spotty: really detailed in some parts, completely missing in others. If you have questions, let me know and I'll clarify. But, @sonyahanson, this is definitely ready for you to read it over.

**Comment by dwhswenson** [comment]
@sonyahanson: Also, please check that I have the correct angle set up in `octomore.py`. I redefined the states based on the results I got out of the angle I’m using as the DFG, but if that angle is wrong, then the specifics of the analysis are wrong. (Of course, the procedure for the analysis will still work for a different state definition.)

**Comment by sonyahanson** [comment]
The angle setup (especially DFG-in / DFG-out definition) might be a bit narrow, but this looks really great. Thanks! (and sorry for being so slow...). I am definitely still skeptical of this order parameter... but that's a larger issue... Will merge.

**Pull request merged**
